name: Release-ArchUnit
on:
  workflow_dispatch:
    inputs:
      oldVersion:
        description: 'You have to provide the current version (e.g. 0.14.0)'
        required: true
      newVersion:
        description: 'You have to provide the new version (e.g. 0.14.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: |
          echo ${{ github.JAVA_HOME_11_X64 }}
          echo $JAVA_HOME_11_X64
          echo $JAVA_HOME
        env:
          JAVA_HOME: ${{ github.JAVA_HOME_11_X64 }}
      - name: Checkout
        run: |
          git clone https://$API_TOKEN_GITHUB@github.com/NilsOliverLinden/ArchUnit.git
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      - name: Build & Validate & Release
        run: |
          cd ArchUnit
          git checkout release-${{ github.event.inputs.newVersion }}

          git config user.name $ACTOR
          git config user.email "action@github.com"

          ./release/release.sh ${{ github.event.inputs.oldVersion }} ${{ github.event.inputs.newVersion }}
        env:
          JAVA_HOME: ${{ github.JAVA_HOME_11_X64 }}
          ACTOR: ${{ github.actor }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSWORD}}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GRADLE_PLUGIN_RELEASE_KEY: ${{ secrets.JGIVEN_GRADLE_PUBLISH_KEY }}
          GRADLE_PLUGIN_RELEASE_PASSWORD: ${{ secrets.JGIVEN_GRADLE_PUBLISH_SECRET }}
